import FDBLean.KleinAction

/-!
# FDBLean.Profiles

The three binary observables induced by the three order-two
subgroups of the nucleotide Klein torsor.

With `A` chosen as origin, the profiles are:

* `R`: orbit under transition substitution `τt`
* `S`: orbit under Watson–Crick complementation `τc`
* `M`: orbit under wobble pairing `τw`

The numerical values are coordinates, not additional biological
structure. Reversing either bit globally gives the same partition.
-/

namespace FDBLean

open Base

/--
The `R` bit, anchored at origin `A`.

`A` and `G` lie in the zero class; `C` and `U` lie in the one class.
This is the orbit partition generated by `tauT`.
-/
def rBit : Base → Bool
  | A => false
  | G => false
  | C => true
  | U => true

/--
The `S` bit, anchored at origin `A`.

`A` and `U` lie in the zero class; `G` and `C` lie in the one class.
This is the orbit partition generated by `tauC`.
-/
def sBit : Base → Bool
  | A => false
  | U => false
  | G => true
  | C => true

/--
The `M` bit, anchored at origin `A`.

`A` and `C` lie in the zero class; `G` and `U` lie in the one class.
This is the orbit partition generated by `tauW`.
-/
def mBit : Base → Bool
  | A => false
  | C => false
  | G => true
  | U => true

/-!
## The XOR law
-/

/--
The three profile bits satisfy the affine relation

`R XOR S = M`.

Equivalently, `R + S + M = 0` over `F₂`.
-/
theorem profile_xor_law
    (b : Base) :
    Bool.xor (rBit b) (sBit b) = mBit b := by
  cases b <;> rfl

/--
The symmetric three-bit form of the XOR law.
-/
theorem profile_total_xor_zero
    (b : Base) :
    Bool.xor (Bool.xor (rBit b) (sBit b)) (mBit b) = false := by
  cases b <;> rfl

/-!
## Action of the three biochemical involutions
-/

/--
Transition substitution preserves the `R` profile.
-/
theorem rBit_tauT
    (b : Base) :
    rBit (tauT b) = rBit b := by
  cases b <;> rfl

/--
Transition substitution flips the `S` profile.
-/
theorem sBit_tauT
    (b : Base) :
    sBit (tauT b) = !(sBit b) := by
  cases b <;> rfl

/--
Transition substitution flips the `M` profile.
-/
theorem mBit_tauT
    (b : Base) :
    mBit (tauT b) = !(mBit b) := by
  cases b <;> rfl

/--
Watson--Crick complementation flips the `R` profile.
-/
theorem rBit_tauC
    (b : Base) :
    rBit (tauC b) = !(rBit b) := by
  cases b <;> rfl

/--
Watson--Crick complementation preserves the `S` profile.
-/
theorem sBit_tauC
    (b : Base) :
    sBit (tauC b) = sBit b := by
  cases b <;> rfl

/--
Watson--Crick complementation flips the `M` profile.
-/
theorem mBit_tauC
    (b : Base) :
    mBit (tauC b) = !(mBit b) := by
  cases b <;> rfl

/--
Wobble pairing flips the `R` profile.
-/
theorem rBit_tauW
    (b : Base) :
    rBit (tauW b) = !(rBit b) := by
  cases b <;> rfl

/--
Wobble pairing flips the `S` profile.
-/
theorem sBit_tauW
    (b : Base) :
    sBit (tauW b) = !(sBit b) := by
  cases b <;> rfl

/--
Wobble pairing preserves the `M` profile.
-/
theorem mBit_tauW
    (b : Base) :
    mBit (tauW b) = mBit b := by
  cases b <;> rfl

/-!
## Any two profiles determine the base
-/

/--
The pair `(R,S)` uniquely determines a nucleotide.
-/
theorem rs_profile_injective :
    Function.Injective (fun b : Base => (rBit b, sBit b)) := by
  intro a b h
  cases a <;> cases b <;>
    simp [rBit, sBit] at h ⊢

/--
The pair `(R,M)` uniquely determines a nucleotide.
-/
theorem rm_profile_injective :
    Function.Injective (fun b : Base => (rBit b, mBit b)) := by
  intro a b h
  cases a <;> cases b <;>
    simp [rBit, mBit] at h ⊢

/--
The pair `(S,M)` uniquely determines a nucleotide.
-/
theorem sm_profile_injective :
    Function.Injective (fun b : Base => (sBit b, mBit b)) := by
  intro a b h
  cases a <;> cases b <;>
    simp [sBit, mBit] at h ⊢

/-!
## Profiles relative to an arbitrary origin

Changing the origin translates the coordinates but does not change
the underlying orbit partitions.
-/

/--
The `R` profile relative to a chosen origin.
-/
def rBitAt (origin b : Base) : Bool :=
  Bool.xor (rBit b) (rBit origin)

/--
The `S` profile relative to a chosen origin.
-/
def sBitAt (origin b : Base) : Bool :=
  Bool.xor (sBit b) (sBit origin)

/--
The `M` profile relative to a chosen origin.
-/
def mBitAt (origin b : Base) : Bool :=
  Bool.xor (mBit b) (mBit origin)

/--
Every relative `R` profile vanishes at its origin.
-/
theorem rBitAt_origin
    (origin : Base) :
    rBitAt origin origin = false := by
  cases origin <;> rfl

/--
Every relative `S` profile vanishes at its origin.
-/
theorem sBitAt_origin
    (origin : Base) :
    sBitAt origin origin = false := by
  cases origin <;> rfl

/--
Every relative `M` profile vanishes at its origin.
-/
theorem mBitAt_origin
    (origin : Base) :
    mBitAt origin origin = false := by
  cases origin <;> rfl

/--
The XOR law is invariant under a change of origin.
-/
theorem relative_profile_xor_law
    (origin b : Base) :
    Bool.xor (rBitAt origin b) (sBitAt origin b) =
      mBitAt origin b := by
  cases origin <;> cases b <;> rfl

/--
For every chosen origin, the relative `(R,S)` profile uniquely
determines the base.
-/
theorem relative_rs_profile_injective
    (origin : Base) :
    Function.Injective
      (fun b : Base => (rBitAt origin b, sBitAt origin b)) := by
  intro a b h
  cases origin <;> cases a <;> cases b <;>
    simp [rBitAt, sBitAt, rBit, sBit] at h ⊢

end FDBLean
